### PR TITLE
Package for TestPyPI release (v 1.0.2)

### PR DESCRIPTION
**Pull request by aiaay**
ngredient function not yet fixed

### CODE REVIEW

**Review by ligon — CHANGES_REQUESTED** [review]
Could you please move ./Data/units.txt to ~/.unitsrc?  Otherwise looks good.

**Review by ligon — COMMENTED** [review]
I meant literally "$HOME/.unitsrc".

That way the code can find the .unitsrc file no matter what the present working directory is for the python interpreter.

**Comment by aiaay** [comment]
OH! I got it now. So, just to confirm, I should just take out the unit.txt
file from the fdc package and only leave the path?

**Comment by ligon** [comment]
Right, though please also be sure the file format is documented with an
example.

**Review by ligon — APPROVED** [review]

**Pull request closed without merging**
